name: Format Markdown

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**.md'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Prettier
        run: npm install -g prettier

      - name: Format Markdown
        run: prettier --write "**/*.md"

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🎨 Format Markdown with Prettier"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"